# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'

resources:
 repositories:
   - repository: emt
     type : github
     name : sbui-axway/emt
     ref : refs/heads/master
     endpoint: sbui-axway
steps:
- checkout: emt
  path: /opt/Axway/source
- task: Bash@3
  inputs:
    filePath: '/opt/Axway/apigateway/posix/bin/projpack'
    arguments: '--create --name=test --add /home/user1/apiprojects/proj1'
  